FROM python:3.6.12-alpine3.12

RUN adduser -D microblog

WORKDIR /home/microblog

# COPY files.
COPY app app
COPY migrations migrations
COPY requirements requirements
COPY requirements.txt microblog.py boot.sh ./

RUN python3 -m venv .venv

RUN apk update \
    && apk add --virtual build-dependencies gcc libffi-dev openssl-dev python3-dev py-pip build-base \
    && .venv/bin/pip3 install --upgrade pip \
    && .venv/bin/pip3 install -r requirements.txt \
    && apk del build-dependencies

ENV FLASK_APP microblog.py

RUN chmod +x boot.sh

RUN chown -R microblog:microblog ./
USER microblog

EXPOSE 5000
ENTRYPOINT ["./boot.sh"]