-
  hosts:
    - database
    - appServer
    - loadBalancer
    - monitoring
  # remote_user: azureuser
  remote_user: "{{ deploy_user }}"
  become: yes
  become_method: sudo
  roles:
    - 10-first-minutes